package main;

public enum Category {
	 EOS_DSLR, EOS_M, EOS_DSLR_BUNDLES, POWERSHOT_ADVANCED_PERFORMANCE, POWERSHOT_LONG_ZOOM, POWERSHOT_NEW_CONCEPT,
	 POWERSHOT_PERFORMANCE_STYLE, POWERSHOT_WATERPROOF, REFURBISHED_EOS, REFURBISHED_POWERSHOT, CLEARANCE_POWERSHOT
}
